---

  -hosts: darkstar

    tasks:

    - name: stop services
      service: name={{item}} state=stopped
      with_items:
      - dsconnect
      - dsgame
      - dssearch

    - name: dump db
      mysql_db: state=dump name=dspdb target=dump.sql

    - name: start services
      service: name={{item}} state=started
      with_items:
      - dsconnect
      - dsgame
      - dssearch
