---
- hosts: darkstar
  become: true
  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "3306"
      - "53445"
      - "54230"
      - "54231"
      - "54001"
      - "54002"
      - "54003"
    firewall_allowed_udp_ports:
      - "54230"
    mysql_root_password: 123qwe
    mysql_databases:
      - name: dspdb
    mysql_users: 
      - name: darkstar
        password: 123qwe
        priv: "dspdb.*:ALL"

  roles:
    - firewall
    - mysql
    - darkstar

