---
- hosts: darkstar
  remote_user: root
  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "3306"
      - "54230"
      - "54231"
      - "54001"
      - "54002"
      - "54003"
    firewall_allowed_tcp_ports:
      - "54230"
    mysql_root_password: 123qwe
    mysql_databases:
      - name: dspdb
    mysql_users: 
      - name: darkstar
        password: 123qwe
        priv: "dspdb.*:ALL"

  roles:
    - geerlingguy.firewall
    - darkstar
    - geerlingguy.mysql


  tasks: 

    - shell: ls darkstar/sql/*
      register: path_files

    - name: put the biscuits in the basket 
      mysql_db: state=import name=dspdb target={{ item }}
      with_items: path_files.stdout_lines

#    - name: set up zoneip

    - name: start the dsconnect processes
      command: screen -d -m -S dsconnect ./dsconnect
      args:
        chdir: darkstar

    - name: start the dsgame processes
      command: screen -d -m -S dsgame ./dsgame
      args:
        chdir: darkstar

    - name: start the dssearch processes
      command: screen -d -m -S dssearch ./dssearch
      args:
        chdir: darkstar
