---

    - name: add ubuntu-toolchain-r repo
      apt_repository: repo='ppa:ubuntu-toolchain-r/test'

    - name: start with an apt
      apt: name={{item}} state=latest
      with_items:
        - git
        - libmysqlclient-dev
        - libluajit-5.1-dev
        - libzmq3-dev
        - autoconf
        - pkg-config
        - build-essential
        - htop
        - g++-5

    - name: add symlinks
      file:
        src: /usr/bin/{{item.src}}
        path: /usr/bin/{{item.dest}}
        state: link
      with_items:
          - {src: 'gcc-5', dest: 'gcc'}
          - {src: 'g++-5', dest: 'g++'}
          - {src: 'cpp-5', dest: 'cpp'}

    - name: copy the zoneip file onto remote host
      copy: src=zoneip.sql dest=./

    - name: set zoneip
      mysql_db: state=import name=dspdb target=zoneip.sql

    - name: Check that the darkstar repo exists
      stat: path=darkstar/README.md
      register: stat_darkstar

    - name: git clone darkstar
      git: repo=https://github.com/DarkstarProject/darkstar.git
           dest=./darkstar
           version=stable
           depth=1
           force=yes
      when: stat_darkstar.stat.exists == False

    - name: run autogen.sh
      command: sh autogen.sh
      args:
        chdir: darkstar

    - name: run configure
      command: ./configure
      args:
        chdir: darkstar

    - name: make darkstar
      command: make -j4
      args:
        chdir: darkstar

    - name: copy conf files
      copy: src={{item}} dest=darkstar/conf/
      with_fileglob:
        - conf/*

    - name: copy the correct version.info into darkstar
      copy: src=version.info dest=darkstar/

    - shell: ls darkstar/sql/*
      register: path_files

    - name: put the biscuits in the basket
      mysql_db: state=import name=dspdb target={{ item }}
      with_items: path_files.stdout_lines

    - name: chown darkstar directory
      file: path=darkstar
            state=directory
            mode=0777
            recurse=yes

      #- name: copy the darkstar upstart files
      #- copy: src={{item}} dest=/etc/init/
      #- with_items:
      #-   - dsconnect.conf
      #-   - dsgame.conf
      #-   - dssearch.conf
      #- tags:
      #-   - startDarkstar

      #- name: start the darkstar services
      #- service: name={{item}} state=started
      #- with_items:
      #-   - dsconnect
      #-   - dsgame
      #-   - dssearch
      #- tags:
      #-   - startDarkstar
